### ISSUE TITLE
conda tf2onnx error

### ISSUE THREAD

**Issue by alibukharai** [conda-forge/tf2onnx-feedstock#26]
### Comment:

I cannot be able to install tf2onnx 
![微信图片_20230131145544](https://user-images.githubusercontent.com/60029742/215688873-b031ef75-5f82-4d0d-b54d-4fb53606d24b.png)

**Comment by hmaarrfk** [comment]
we don't really have tensorflow working on windows. 

See 
github.com/conda-forge/tensorflow-feedstock/
